# Generated by Django 2.2.7 on 2019-11-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='boast_roast',
            field=models.BooleanField(choices=[(True, 'Boast'), (False, 'Roast')], default=True),
        ),
    ]
